# Site settings
title:  Jeremy Klein Portfolio
email: jeremyk23@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeremyklein.co" # the base hostname & protocol for your site
twitter_username: jeremyk9123
github_username:  jeremyk23
permalink: /:categories/:title.html
# Build settings
markdown: kramdown
